
"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { styled, createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Sidebar from "./components/Sidebar";
import { useState } from "react";
import MuiDrawer from '@mui/material/Drawer';
const inter = Inter({ subsets: ["latin"] });
import MuiAppBar, { AppBarProps as MuiAppBarProps } from '@mui/material/AppBar';
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState(false);
  const toggleDrawer = () => {
    setOpen(!open);
  };

  return (

    <html lang="en">

      <body className={inter.className}>
        <CssBaseline />
        <Header  open={open} toggleDrawer={toggleDrawer}/>
        <Sidebar open={open} toggleDrawer={toggleDrawer} />
        <div style={{ marginTop: '-38rem', marginLeft: open ? '0px' : '0' }}>
        {children}
        </div>

      </body>

    </html>

  );
}
